name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.8"

      - name: Install dependencies
        run: ./prerequisites.ubuntu.sh

      - name: Build
        run: ./build.sh
