name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.7"

      - name: Install dependencies
        run: ./prerequisites.ubuntu.sh

      - name: Build
        run: ./build.sh
